version: "2.1"

networks:
  loki:

services:
  loki:
    container_name: HowHow-Loki
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - /mnt/rawdata/howhow/loki/config:/etc/loki/
      - /mnt/rawdata/howhow/loki/data:/loki/  
      
  grafana:
    container_name: HowHow-Grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki