version: '2.2'

services:
  howhowmongo:
    image: mongo
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://howhowmongo:27017/

  app:
    build: .
    restart: unless-stopped
    environment:
      - myMongoIP=howhowmongo
      - JKFcookie=
